CREATE TABLE IF NOT EXISTS emprendimento_geracao_distribuida (
  _id INTEGER PRIMARY KEY,
  DatGeracaoConjuntoDados TEXT,
  AnmPeriodoReferencia TEXT,
  NumCNPJDistribuidora TEXT,
  SigAgente TEXT,
  NomAgente TEXT,
  CodClasseConsumo TEXT,
  DscClasseConsumo TEXT,
  CodSubGrupoTarifario TEXT,
  DscSubGrupoTarifario TEXT,
  CodUFibge TEXT,
  SigUF TEXT,
  CodRegiao TEXT,
  NomRegiao TEXT,
  CodMunicipioIbge TEXT,
  NomMunicipio TEXT,
  CodCEP TEXT,
  SigTipoConsumidor TEXT,
  NumCPFCNPJ TEXT,
  NomTitularEmpreendimento TEXT,
  CodEmpreendimento TEXT,
  DthAtualizaCadastralEmpreend TEXT,
  SigModalidadeEmpreendimento TEXT,
  DscModalidadeHabilitado TEXT,
  QtdUCRecebeCredito TEXT,
  SigTipoGeracao TEXT,
  DscFonteGeracao TEXT,
  DscPorte TEXT,
  NumCoordNEmpreendimento TEXT,
  NumCoordEEmpreendimento TEXT,
  MdaPotenciaInstaladaKW TEXT,
  NomSubEstacao TEXT,
  NumCoordESub TEXT,
  NumCoordNSub TEXT
);
